name: Firebase Hosting Continuous Deployment

on: [ push ]
 # push:
 #  branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: cp -R build/web/* webdeploy/public/
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting  --project solid-citadel-247806
        env:
          FIREBASE_TOKEN: ${{ secrets.firebase_key }}
